// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4s8THQi3Vi2bodrv3APNh59VTroCS-go',
    appId: '1:474832457897:web:02283721a5ed9893ee19b8',
    messagingSenderId: '474832457897',
    projectId: 'studnotestt',
    authDomain: 'studnotestt.firebaseapp.com',
    storageBucket: 'studnotestt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMdtNwy6BQWYblACvztRY33W2Dk--QjiQ',
    appId: '1:474832457897:android:34eb2b39276c0e42ee19b8',
    messagingSenderId: '474832457897',
    projectId: 'studnotestt',
    storageBucket: 'studnotestt.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4s8THQi3Vi2bodrv3APNh59VTroCS-go',
    appId: '1:474832457897:web:a987a4f7d3b65795ee19b8',
    messagingSenderId: '474832457897',
    projectId: 'studnotestt',
    authDomain: 'studnotestt.firebaseapp.com',
    storageBucket: 'studnotestt.appspot.com',
  );
}
